 SELECT * FROM cloud.clients WHERE clients.login IS NULL;
-- Удаление существующей таблицы
DROP TABLE IF EXISTS "cloud".clients;

-- Создание новой таблицы
CREATE TABLE "cloud".clients (
                              login VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
                              password VARCHAR(255) NOT NULL
);

-- Вставка новых данных
INSERT INTO "cloud".clients (login, password)
VALUES
    ('user@test.org', 'P@ssw0rd'),
    ('admin@test.org', 'P@ssw0rd');
 CREATE TABLE cloud.files (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              filename VARCHAR(255),
                              filepath VARCHAR(255),
                              filesize BIGINT NOT NULL,
                              PRIMARY KEY (id)
 );