version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud_storage
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Qwerty123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
