server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: user
    password: Qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

#security:
#  jwt:
#    secret: "mySecretKey"
#    expiration: 86400000 # in milliseconds (1 day)
